include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules for pub.dev
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
