name: Publish to pub.dev

on:
  workflow_dispatch:

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      # Format the code
      - name: Format code
        run: dart format lib
      
      # Publish to pub.dev
      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
