name: Publish to pub.dev

on:
  workflow_dispatch:

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      # Install dependencies
      # - name: Install dependencies
      #   run: dart pub get
      
      # Format the code
      - name: Format code
        run: dart format lib
      
      # Publish to pub.dev
      - name: Publish
        run: dart pub publish --force
